Repository evaneliasyoung/Monopolyopoly, pull requests merged in 2022-10, with the labels that each got.

#12 Token and Board Models
  Assets/PrefabModels.meta
  Assets/PrefabModels/Board.meta
  Assets/PrefabModels/Board/Board.prefab
  Assets/PrefabModels/Board/Board.prefab.meta
  Assets/PrefabModels/Board/Dependencies.meta
  Assets/PrefabModels/Board/Dependencies/Board.blend
  Assets/PrefabModels/Board/Dependencies/Board.blend.meta
  Assets/PrefabModels/Board/Dependencies/Board.blend1
  Assets/PrefabModels/Board/Dependencies/Board.blend1.meta
  Assets/PrefabModels/Board/Dependencies/Board.fbx
  Assets/PrefabModels/Board/Dependencies/Board.fbx.meta
  Assets/PrefabModels/Board/Dependencies/basicMonopolyTex.jpg
  Assets/PrefabModels/Board/Dependencies/basicMonopolyTex.jpg.meta
  Assets/PrefabModels/Board/Dependencies/boardBorderMat.mat
  Assets/PrefabModels/Board/Dependencies/boardBorderMat.mat.meta
  Assets/PrefabModels/Board/Dependencies/monopolyBoardMat.mat
  Assets/PrefabModels/Board/Dependencies/monopolyBoardMat.mat.meta
  Assets/PrefabModels/Tokens.meta
  Assets/PrefabModels/Tokens/BowToken.prefab
  Assets/PrefabModels/Tokens/BowToken.prefab.meta
  Assets/PrefabModels/Tokens/CrowbarToken.prefab
  Assets/PrefabModels/Tokens/CrowbarToken.prefab.meta
  Assets/PrefabModels/Tokens/Dependencies.meta
  Assets/PrefabModels/Tokens/Dependencies/BowToken.fbx
  Assets/PrefabModels/Tokens/Dependencies/BowToken.fbx.meta
  Assets/PrefabModels/Tokens/Dependencies/CrowbarToken.fbx
  Assets/PrefabModels/Tokens/Dependencies/CrowbarToken.fbx.meta
  Assets/PrefabModels/Tokens/Dependencies/MoneyToken.fbx
  Assets/PrefabModels/Tokens/Dependencies/MoneyToken.fbx.meta
  Assets/PrefabModels/Tokens/Dependencies/MonopolyPieces.blend
  Assets/PrefabModels/Tokens/Dependencies/MonopolyPieces.blend.meta
  Assets/PrefabModels/Tokens/Dependencies/MonopolyPieces.blend1
  Assets/PrefabModels/Tokens/Dependencies/MonopolyPieces.blend1.meta
  Assets/PrefabModels/Tokens/Dependencies/metalMat.mat
  Assets/PrefabModels/Tokens/Dependencies/metalMat.mat.meta
  Assets/PrefabModels/Tokens/Dependencies/roughMetalNormal.jpg
  Assets/PrefabModels/Tokens/Dependencies/roughMetalNormal.jpg.meta
  Assets/PrefabModels/Tokens/MoneyToken.prefab
  Assets/PrefabModels/Tokens/MoneyToken.prefab.meta
  Assets/Scenes.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
Labels: enhancement

#11 Add Property Structure
  .vscode/extensions.json
  Assets/Lib.meta
  Assets/Lib/Enumerations.meta
  Assets/Lib/Enumerations/TileType.cs
  Assets/Lib/Enumerations/TileType.cs.meta
  Assets/Lib/Interfaces.meta
  Assets/Lib/Interfaces/IHousingProvider.cs
  Assets/Lib/Interfaces/IHousingProvider.cs.meta
  Assets/Lib/Interfaces/IProperty.cs
  Assets/Lib/Interfaces/IProperty.cs.meta
  Assets/Lib/Interfaces/IStreet.cs
  Assets/Lib/Interfaces/IStreet.cs.meta
  Assets/Lib/Interfaces/ITileSpace.cs
  Assets/Lib/Interfaces/ITileSpace.cs.meta
  Assets/Lib/Interfaces/IWithIndex.cs
  Assets/Lib/Interfaces/IWithIndex.cs.meta
  Assets/Lib/Property.cs
  Assets/Lib/Property.cs.meta
  Assets/Lib/Street.cs
  Assets/Lib/Street.cs.meta
  Assets/Lib/TileSpace.cs
  Assets/Lib/TileSpace.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#28 Add residence bounds checking
  Assets/Lib/Bank.cs
Labels: bug

#33 Bank UI Redux
  Assets/Lib/Bank.cs
  Assets/Lib/Property.cs
  Assets/Lib/Street.cs
  Assets/Lib/TileSpace.cs
Labels: bug, enhancement
